#!/usr/bin/env python3

from i3ipc import Connection, Event

i3 = Connection()


def adjust_gaps(self, e):
    tree = i3.get_tree()
    focused = tree.find_focused()
    workspace = focused.workspace()
    workspace_leaves = len(workspace.leaves())
    floating_nodes = len(workspace.floating_nodes)
    window_count = workspace_leaves - floating_nodes
    if window_count == 1:
        i3.command("gaps horizontal current set 575")
    elif window_count == 2:
        i3.command("gaps horizontal current set 256")
    else:
        i3.command("gaps horizontal current set 5")


i3.on(Event.WINDOW_NEW, adjust_gaps)
i3.on(Event.WINDOW_CLOSE, adjust_gaps)

i3.main()
