#!/bin/bash
#
# Mark all urgent windows as read.

for ((n = 0; n < 40; n++)); do
  for win in $(wmctrl -l | awk -F' ' '{print $1}'); do
    wmctrl -i -r "${win}" -b remove,demands_attention
  done
  sleep .25
done
