#!/bin/bash
#
# Graceful exit for sway window manager.

TIMEOUT=10

# close all windows
swaymsg '[title="."] kill'
sleep 1

# check if windows are still running
for i in $(seq 0 $((TIMEOUT - 1))); do
  [[ $(swaymsg -t get_tree | jq '[ .. | objects | select(.type == "con") ] | length') = 0 ]] && break
  echo "Forceful termination in $((TIMEOUT - i)).."
  notify-send "Graceful $1" "Forceful termination in $((TIMEOUT - i)).."
  sleep 1
done

# bye
case "$1" in
  exit) swaymsg exit ;;
  poweroff) systemctl poweroff ;;
  reboot) systemctl reboot ;;
  *) exit 1 ;;
esac
