#! /bin/sh

# autostart apps
sxhkd &
nitrogen --restore &
volumeicon &
$HOME/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xfce4-power-manager &
xautolock -time 10 -locker blurlock &
ff-theme-util &
fix_xcursor &
compton -b &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true

bspc config border_width 1
bspc config normal_border_color  '#303030'
bspc config active_border_color  '#303030'
bspc config focused_border_color '#FFB86C'

bspc config top_padding 26
bspc config window_gap 12

bspc config automatic_scheme   longest_side
bspc config split_ratio        0.50
bspc config single_monocle     true
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc rule -a Firefox   desktop='^2'
bspc rule -a Chromium  desktop='^2'
bspc rule -a Screenkey manage=off
