git:
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers-left-format='{nm}⫶' --line-numbers-right-format='{np}|' --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  log:
    showGraph: when-maximised

gui:
  commitHashLength: 4
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: arrowAndNumber
  switchTabsWithPanelJumpKeys: true
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"

keybinding:
  universal:
    openFile: <disabled>
    # nextScreenMode: "="
    # prevScreenMode: "-"

notARepository: "skip"
promptToReturnFromSubprocess: false

customCommands:
  - key: "D"
    context: "localBranches"
    command: "git reset --hard {{.SelectedRemote.Name}}/{{.SelectedLocalBranch.Name}}"
    prompts:
      - type: "confirm"
        title: "Hard reset"
        body: "Are you sure you want to hard reset the current head?"
