gui:
  nerdFontsVersion: "3"
  commitHashLength: 4
  theme:
    cherryPickedCommitFgColor:
      - "#82aaff"
    defaultFgColor:
      - "#c8d3f5"
    inactiveBorderColor:
      - "#589ed7"
    optionsTextColor:
      - "#82aaff"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    selectedLineBgColor:
      - "#2d3f76"
    unstagedChangesColor:
      - "#c53b53"
    activeBorderColor:
      - "#ff966c"
      - "bold"
    cherryPickedCommitBgColor:
      - "#c099ff"
notARepository: "skip"
promptToReturnFromSubprocess: false
