"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = "l", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "<Right>", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on =  "f" , run = "cd --interactive" },
  { on = "F", run = "filter --smart", desc = "Filter files" },
  { on = "d", run = "remove --permanently", desc = "Permanently delete selected files" },
  { on = "<Delete>", run = "remove", desc = "Trash selected files" },
  { on = "<C-u>", run = "arrow -25%",  desc = "Move cursor up half page" },
  { on = "<C-d>", run = "arrow 25%",   desc = "Move cursor down half page" },
  { on = "<C-b>", run = "arrow -50%", desc = "Move cursor up one page" },
  { on = "<C-f>", run = "arrow 50%",  desc = "Move cursor down one page" },
  { on = "<C-s>", run  = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  { on = "<A-j>", run = "plugin --sync parent-arrow --args=1" },
  { on = "<A-k>", run = "plugin --sync parent-arrow --args=-1" },
]

append_keymap = [
  { on = [ "g", "b" ], run = "cd ~/.local/bin" },
  { on = [ "g", "c" ], run = "cd ~/.config" },
  { on = [ "g", "d" ], run = "cd ~/Downloads" },
  { on = [ "g", "h" ], run = "cd ~" },
  { on = [ "g", "m" ], run = "cd ~/media" },
  { on = [ "g", "P" ], run = "cd ~/Pictures" },
  { on = [ "g", "p" ], run = "cd ~/projects" },
  { on = [ "g", "r" ], run = "cd ~/repos" },
  { on = [ "g", "t" ], run = "cd ~/tmp" },
  { on = [ "g", "T" ], run = "cd /tmp" },
]


[completion]
append_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<C-j>", run = "arrow 1",  desc = "Move cursor down" },
]
