"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
	{ on = "l", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
	{ on = "<Right>", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on =  "f" , run = "cd --interactive" },
  { on = "F", run = "filter --smart", desc = "Filter files" },
]
append_keymap = [
  { on = [ "g", "b" ], run = "cd ~/.local/bin" },
  { on = [ "g", "c" ], run = "cd ~/.config" },
  { on = [ "g", "d" ], run = "cd ~/Downloads" },
  { on = [ "g", "h" ], run = "cd ~" },
  { on = [ "g", "m" ], run = "cd ~/media" },
  { on = [ "g", "P" ], run = "cd ~/Pictures" },
  { on = [ "g", "p" ], run = "cd ~/projects" },
  { on = [ "g", "r" ], run = "cd ~/repos" },
  { on = [ "g", "t" ], run = "cd ~/tmp" },
  { on = [ "g", "T" ], run = "cd /tmp" },
]


[completion]
append_keymap = [
	{ on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
	{ on = "<C-j>", run = "arrow 1",	desc = "Move cursor down" },
]
