"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode = "size"

[open]
rules = [
  { name = "*/", use = [ "edit", "open", "reveal" ] },

  { mime = "text/*",          use = [ "edit", "reveal" ] },
  { mime = "image/*",         use = [ "open", "reveal" ] },
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  { name = "*.mp4.part",      use = [ "play", "reveal" ] },
  { mime = "inode/x-empty",   use = [ "edit", "reveal" ] },

  { mime = "application/*zip", use = [ "extract", "reveal" ] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },

  { mime = "application/json",     use = [ "edit", "reveal" ] },
  { mime = "application/x-subrip", use = [ "edit", "reveal" ] },
  { mime = "*/javascript",         use = [ "edit", "reveal" ] },

  { mime = "application/pdf", use = [ "open", "reveal" ] },

  # { mime = "*", use = [ "reveal" ] },
  { mime = "*", use = [] },
]
